//! Compiles a user's Rust indicator source to a `wasm32-wasip2` component.
//!
//! # Why this exists as its own crate, with no domain dependency
//!
//! This is the "level 2" compile path: authoring inside
//! the application, where the server itself runs `cargo build` on
//! whatever a user typed. That is real code execution on the machine
//! running Senken, before the WASM sandbox
//! `senken-plugin-host` enforces at *runtime* exists at all — `cargo`
//! itself can run a dependency's `build.rs` or a proc macro. What closes
//! that off here is not a sandbox around `cargo`, but that the generated
//! crate this service builds **has no dependency but `senken-plugin-api`**
//! and no `build.rs` of its own — its `Cargo.toml` is generated by
//! [`CompileService`] itself on every compile, never accepted from a
//! caller. See this crate's `README.md` for the fuller version.
//!
//! Keeping this crate free of `senken-acl`/`senken-identity`/database
//! access is deliberate, not an oversight: it runs a process and turns its
//! output into a typed result, nothing else. Whose indicator this is,
//! where the source and result are stored, and what HTTP endpoint exposes
//! it are `senken-api`'s `user_indicator_handlers` and
//! `senken-indicator-registry::UserIndicatorStore`'s job.
//!
//! # Assumptions, stated rather than guessed
//!
//! [`Toolchain::detect`] and [`CompileService::compile`]'s source
//! rejection are both explicitly documented at their own definitions as
//! assumptions rather than derived from a specification — see each for
//! what is assumed and why.

mod service;
mod toolchain;

pub use crate::service::{CompileError, CompileRequest, CompileService, Diagnostic};
pub use crate::toolchain::{TARGET, Toolchain, ToolchainError};
